#!/bin/bash
g++ -Wno-deprecated -fPIC  $1 -o $2 -I$ROOTSYS/include -I$CLHEP_PARAM_PATH/include -L${ROOTSYS}/lib -lRint -lTree -lTreePlayer -lCint -lThread -lGraf -lGraf3d -lSmatrix  -lHist -lHtml -lMinuit -lPostscript -lProof -lThread -lCore -lGX11 -lPhysics -lGpad -lGui -lTreeViewer -lvectorDict -L$CLHEP_PARAM_PATH/lib -lCLHEP -L/usr/X11R6/lib -lm -ldl -L/usr/lib -lpthread -rdynamic
 
